import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getNextSequenceValue } from "@/lib/sequences";
import { logTransaction } from "@/lib/transaction-log";
import { FeeStatus, FeeType } from "@prisma/client";

// This endpoint automatically checks if fee vouchers need to be generated
// It's called when the dashboard loads or system starts up
// It will generate vouchers for the current month if they haven't been generated yet

export async function POST(request: NextRequest) {
  try {
    // Allow both CRON secret and authenticated admin users
    const authHeader = request.headers.get("authorization");
    const cronSecret = process.env.CRON_SECRET;
    const session = await getServerSession(authOptions);

    const isAuthorizedByCron =
      cronSecret && authHeader === `Bearer ${cronSecret}`;
    const isAuthorizedBySession =
      session?.user?.role === "SUPER_ADMIN" || session?.user?.role === "ADMIN";

    if (!isAuthorizedByCron && !isAuthorizedBySession) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const now = new Date();
    const targetMonth = now.getMonth() + 1; // 1-12
    const targetYear = now.getFullYear();

    // Check if vouchers have already been generated for this month
    const existingVouchersCount = await prisma.feeVoucher.count({
      where: {
        month: targetMonth,
        year: targetYear,
        isAutoGenerated: true,
      },
    });

    // Get count of active students
    const activeStudentsCount = await prisma.student.count({
      where: { status: "ACTIVE" },
    });

    // If most students already have vouchers, skip generation
    // Allow some tolerance (90%) in case some students were added mid-month
    if (
      existingVouchersCount >= activeStudentsCount * 0.9 &&
      activeStudentsCount > 0
    ) {
      return NextResponse.json({
        success: true,
        message: "Fee vouchers already generated for this month",
        stats: {
          month: targetMonth,
          year: targetYear,
          existingVouchers: existingVouchersCount,
          activeStudents: activeStudentsCount,
          action: "skipped",
        },
      });
    }

    // Need to generate vouchers - proceed with generation
    console.log(
      `[AUTO-CHECK] Starting fee voucher generation for ${targetMonth}/${targetYear}`
    );

    const dueDate = new Date(targetYear, targetMonth - 1, 10); // Due on 10th

    // Get current academic year
    const academicYear = await prisma.academicYear.findFirst({
      where: { isCurrent: true },
    });

    if (!academicYear) {
      return NextResponse.json({
        success: false,
        message: "No active academic year found",
        action: "failed",
      });
    }

    // Get all active students with their class info
    const students = await prisma.student.findMany({
      where: { status: "ACTIVE" },
      include: {
        class: true,
        section: true,
      },
    });

    // Get fee structures for recurring fees
    const feeStructures = await prisma.feeStructure.findMany({
      where: {
        academicYearId: academicYear.id,
        isActive: true,
        isRecurring: true,
      },
    });

    let created = 0;
    let skipped = 0;
    let errors = 0;

    for (const student of students) {
      try {
        // Check if voucher already exists
        const existingVoucher = await prisma.feeVoucher.findFirst({
          where: {
            studentId: student.id,
            month: targetMonth,
            year: targetYear,
          },
        });

        if (existingVoucher) {
          skipped++;
          continue;
        }

        // Get applicable fee structures for student's class
        const applicableFees = feeStructures.filter(
          (fs) => !fs.classId || fs.classId === student.classId
        );

        if (applicableFees.length === 0 && student.monthlyFee === 0) {
          skipped++;
          continue;
        }

        // Calculate total amount
        let totalAmount = student.monthlyFee || 0;
        const feeItems: {
          feeType: FeeType;
          description: string;
          amount: number;
        }[] = [];

        if (student.monthlyFee > 0) {
          feeItems.push({
            feeType: FeeType.MONTHLY_FEE,
            description: `Monthly Fee - ${targetMonth}/${targetYear}`,
            amount: student.monthlyFee,
          });
        }

        for (const fee of applicableFees) {
          if (fee.feeType !== FeeType.MONTHLY_FEE) {
            totalAmount += fee.amount;
            feeItems.push({
              feeType: fee.feeType,
              description: fee.name,
              amount: fee.amount,
            });
          }
        }

        // Get previous balance (unpaid from last voucher)
        const lastVoucher = await prisma.feeVoucher.findFirst({
          where: { studentId: student.id },
          orderBy: { createdAt: "desc" },
        });

        const previousBalance = lastVoucher
          ? lastVoucher.totalAmount - lastVoucher.paidAmount
          : 0;

        // Generate voucher number
        const voucherNo = await getNextSequenceValue("VOUCHER");

        // Create voucher with fee items
        await prisma.feeVoucher.create({
          data: {
            voucherNo,
            studentId: student.id,
            month: targetMonth,
            year: targetYear,
            dueDate,
            subtotal: totalAmount,
            previousBalance,
            totalAmount: totalAmount + previousBalance,
            paidAmount: 0,
            balanceDue: totalAmount + previousBalance,
            status: FeeStatus.UNPAID,
            isAutoGenerated: true,
            createdById: "system",
            feeItems: {
              create: feeItems,
            },
            previousVoucherId: lastVoucher?.id,
          },
        });

        created++;
      } catch (err) {
        console.error(
          `[AUTO-CHECK] Error generating voucher for student ${student.id}:`,
          err
        );
        errors++;
      }
    }

    // Update vouchers that are past due date to OVERDUE status
    const overdueCount = await prisma.feeVoucher.updateMany({
      where: {
        status: FeeStatus.UNPAID,
        dueDate: { lt: now },
      },
      data: {
        status: FeeStatus.OVERDUE,
      },
    });

    console.log(
      `[AUTO-CHECK] Completed. Created: ${created}, Skipped: ${skipped}, Errors: ${errors}, Marked Overdue: ${overdueCount.count}`
    );

    return NextResponse.json({
      success: true,
      message: `Fee voucher generation completed`,
      stats: {
        month: targetMonth,
        year: targetYear,
        totalStudents: students.length,
        vouchersCreated: created,
        skipped,
        errors,
        markedOverdue: overdueCount.count,
        action: "generated",
      },
    });
  } catch (error) {
    console.error("[AUTO-CHECK] Fee voucher check failed:", error);
    return NextResponse.json(
      { error: "Fee voucher check failed" },
      { status: 500 }
    );
  }
}

// GET endpoint to check if generation is needed
export async function GET() {
  try {
    const now = new Date();
    const currentMonth = now.getMonth() + 1;
    const currentYear = now.getFullYear();

    const [activeStudents, vouchersThisMonth] = await Promise.all([
      prisma.student.count({ where: { status: "ACTIVE" } }),
      prisma.feeVoucher.count({
        where: {
          month: currentMonth,
          year: currentYear,
          isAutoGenerated: true,
        },
      }),
    ]);

    const needsGeneration =
      vouchersThisMonth < activeStudents * 0.9 && activeStudents > 0;

    return NextResponse.json({
      currentMonth,
      currentYear,
      activeStudents,
      vouchersThisMonth,
      needsGeneration,
    });
  } catch (error) {
    return NextResponse.json(
      { error: "Failed to check status" },
      { status: 500 }
    );
  }
}
